# Generated by Django 5.2 on 2025-04-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
    ]
