# Generated by Django 5.2 on 2025-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_destination_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourguide',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
