# Generated by Django 5.2 on 2025-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tourguide_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
