# Generated by Django 5.2 on 2025-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='hotel-rooms/'),
        ),
    ]
