# Generated by Django 5.2 on 2025-04-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_hotelroom_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image_cover',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
    ]
