# Generated by Django 5.2 on 2025-04-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_hotel_image_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdestination',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='order_in_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
