# Generated by Django 5.2 on 2025-04-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tourdestination_end_time_tourdestination_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourdestination',
            name='day_number',
        ),
    ]
