# Generated by Django 5.2 on 2025-04-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_tourdestination_day_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdestination',
            name='order_in_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
