# Generated by Django 5.2 on 2025-04-28 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_tourdestination_order_in_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorbike', 'Motorbike'), ('bus', 'Bus'), ('bicycle', 'Bicycle'), ('van', 'Van'), ('other', 'Other')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('seat_count', models.IntegerField(default=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('is_available', models.BooleanField(default=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiclerental',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='vehiclerental',
            name='vehicle_brand',
        ),
        migrations.RemoveField(
            model_name='vehiclerental',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='vehiclerental',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerental',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.destination'),
        ),
        migrations.AddField(
            model_name='vehiclerental',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle'),
        ),
    ]
