# Generated by Django 5.2 on 2025-04-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_roomtype_alter_hotelroom_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
