# Generated by Django 5.2 on 2025-04-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_hotelroom_room_type_delete_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
