# Generated by Django 5.2 on 2025-05-01 11:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_hotelamenity_alter_hotelroom_hotel_hotel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='amenties', to='api.hotelamenity'),
        ),
    ]
