# Generated by Django 5.2 on 2025-05-01 12:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_destination_description_alter_hotel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
