# Generated by Django 5.0.14 on 2025-05-03 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_tour_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='available_dates',
        ),
        migrations.AlterField(
            model_name='tourdestination',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='api.destination'),
        ),
        migrations.AlterField(
            model_name='tourdestination',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourDestination', to='api.tour'),
        ),
    ]
