# Generated by Django 5.0.14 on 2025-05-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_tour_available_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='available_dates',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
