# Generated by Django 5.0.14 on 2025-05-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_tour_available_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='available_dates',
            field=models.DateField(blank=True, null=True),
        ),
    ]
