# Generated by Django 5.0.14 on 2025-05-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_tour_available_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
