# Generated by Django 5.0.14 on 2025-05-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_price',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
