# Generated by Django 5.0.14 on 2025-05-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_event_festival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='events-news/'),
        ),
    ]
