# Generated by Django 5.0.14 on 2025-05-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_tour_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='slug',
        ),
    ]
