# Generated by Django 5.0.14 on 2025-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='amenties_rooms', to='api.hotelamenity'),
        ),
    ]
