# Generated by Django 5.0.14 on 2025-05-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_hotelroom_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
