# Generated by Django 5.0.14 on 2025-05-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_roombooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
