# Generated by Django 5.0.14 on 2025-05-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_article_cover_image_url_alter_client_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
    ]
