# Generated by Django 5.0.14 on 2025-05-12 15:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_destination_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
