# Generated by Django 5.0.14 on 2025-05-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_destination_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotiontransportation',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='promotionhotel',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='promotiontour',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='promotionhotel',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='promotiontour',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='promotiontransportation',
            name='transportation',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='PromotionHotel',
        ),
        migrations.DeleteModel(
            name='PromotionTour',
        ),
        migrations.DeleteModel(
            name='PromotionTransportation',
        ),
    ]
