# Generated by Django 5.0.14 on 2025-05-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_destination_ticket_price_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
